name: Build

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    flutter-build-linux:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v6

          - name: Setup Flutter
            uses: subosito/flutter-action@v2
            with:
                channel: stable
                cache: true

          - name: Install build deps
            run: |
                sudo apt-get update
                sudo apt-get install -y \
                clang \
                cmake \
                ninja-build \
                pkg-config \
                libgtk-3-dev \
                liblzma-dev \
                libgstreamer1.0-dev \
                libgstreamer-plugins-base1.0-dev

          - run: flutter pub get

          - name: Build release bundle (Linux)
            run: flutter build linux --release

          - name: Zip bundle
            run: |
                cd build/linux/x64/release
                ZIP_NAME=pomodoro-linux-${{ github.ref_name }}.zip
                zip -r $ZIP_NAME bundle
                echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

          - name: Create release
            uses: softprops/action-gh-release@v2
            with:
                files: ${{ env.ZIP_NAME }}
                generate_release_notes: true
